### ISSUE TITLE
Can we do a new release for 9.10.1

### ISSUE THREAD

**Issue by soulomoon** [conal/vector-space#31]
HLS's benchmark for 9.10.1 is blocked

**Comment by conal** [comment]
What do you need beyond #30?

**Comment by soulomoon** [comment]
#30 is enough, but https://hackage.haskell.org/package/vector-space do not have this new version yet?

**Comment by conal** [comment]
Thanks. [Released.](https://hackage.haskell.org/package/vector-space-0.19)
